import { getItineraries } from "../actions";
import Link from "next/link";
import { Search, MapPin, Calendar, ArrowUp, MessageSquare, Sparkles, Filter, RefreshCw } from "lucide-react";

export default async function ExplorePage({ searchParams }) {
  const resolvedSearchParams = await searchParams;
  const query = resolvedSearchParams?.q || "";
  const budget = resolvedSearchParams?.budget || "All";
  const duration = resolvedSearchParams?.duration || "All";
  const tab = resolvedSearchParams?.tab || "all";

  // Fetch filtered itineraries
  const itineraries = await getItineraries(query, { budget, duration, tab });

  // Helper to build URLs maintaining active filters
  const getFilterUrl = (key, value) => {
    const params = new URLSearchParams();
    if (query) params.set("q", query);
    if (budget !== "All") params.set("budget", budget);
    if (duration !== "All") params.set("duration", duration);
    if (tab !== "all") params.set("tab", tab);

    if (value === "All" || value === "all") {
      params.delete(key);
    } else {
      params.set(key, value);
    }

    const queryStr = params.toString();
    return `/explore${queryStr ? `?${queryStr}` : ""}`;
  };

  return (
    <div className="explore-container">
      {/* Header */}
      <div className="explore-header">
        <h1 className="explore-title">
          Explore Travel <span>Itineraries</span>
        </h1>
        <p className="explore-subtitle">
          Find, verify, and copy plans shared by the community or generated by AI.
        </p>
      </div>

      {/* Search Input Container */}
      <form action="/explore" method="GET" className="search-container">
        {budget !== "All" && <input type="hidden" name="budget" value={budget} />}
        {duration !== "All" && <input type="hidden" name="duration" value={duration} />}
        {tab !== "all" && <input type="hidden" name="tab" value={tab} />}
        
        <button type="submit" className="search-icon-btn">
          <Search size={20} />
        </button>
        <input
          type="text"
          name="q"
          defaultValue={query}
          placeholder="Search by destination or keyword (e.g. Delhi, Paris, Fuji)..."
          className="search-input"
        />
      </form>

      {/* Tabs (All, Community, AI) */}
      <div className="explore-tabs">
        <Link 
          href={getFilterUrl("tab", "all")} 
          className={`tab-btn ${tab === "all" ? "active" : ""}`}
        >
          All Guides
        </Link>
        <Link 
          href={getFilterUrl("tab", "community")} 
          className={`tab-btn ${tab === "community" ? "active" : ""}`}
        >
          👤 Community
        </Link>
        <Link 
          href={getFilterUrl("tab", "ai")} 
          className={`tab-btn ${tab === "ai" ? "active" : ""}`}
        >
          ✨ AI Planner
        </Link>
      </div>

      {/* Filter Panel */}
      <div className="filter-panel">
        <div className="filter-row">
          <div className="filter-group">
            <div className="filter-label">
              <Filter size={14} /> FILTERS
            </div>

            {/* Budget Filter */}
            <div className="filter-item">
              <span className="filter-item-title">Budget:</span>
              <div className="filter-chips">
                {["All", "Budget", "Mid-range", "Luxury"].map((b) => (
                  <Link
                    key={b}
                    href={getFilterUrl("budget", b)}
                    className={`filter-chip ${budget === b ? "active" : ""}`}
                  >
                    {b}
                  </Link>
                ))}
              </div>
            </div>

            {/* Duration Filter */}
            <div className="filter-item">
              <span className="filter-item-title">Duration:</span>
              <div className="filter-chips">
                {[
                  { label: "All", value: "All" },
                  { label: "1-3d", value: "short" },
                  { label: "4-7d", value: "medium" },
                  { label: "8d+", value: "long" }
                ].map((d) => (
                  <Link
                    key={d.value}
                    href={getFilterUrl("duration", d.value)}
                    className={`filter-chip ${duration === d.value ? "active" : ""}`}
                  >
                    {d.label}
                  </Link>
                ))}
              </div>
            </div>
          </div>

          {/* Reset Filters Option */}
          {(query || budget !== "All" || duration !== "All" || tab !== "all") && (
            <Link href="/explore" className="btn-clear-filters">
              <RefreshCw size={12} /> Clear
            </Link>
          )}
        </div>
      </div>

      {/* Results Header */}
      <div className="results-header">
        <h2 className="results-title">
          {query ? `Search Results for "${query}"` : `${tab === "ai" ? "AI Generated" : tab === "community" ? "Community" : "Trending"} Guides`}
        </h2>
        <span className="results-count">
          Showing {itineraries.length} guides
        </span>
      </div>

      {/* Itineraries Grid */}
      {itineraries.length === 0 ? (
        <div className="empty-state">
          <MapPin size={48} className="empty-state-icon" />
          <h3>No itineraries found</h3>
          <p>
            Adjust your search query or remove active filters to browse more itineraries.
          </p>
        </div>
      ) : (
        <div className="itinerary-grid">
          {itineraries.map((it) => {
            const upvotes = it.votes?.filter((v) => v.vote_type === "upvote").length || 0;
            const downvotes = it.votes?.filter((v) => v.vote_type === "downvote").length || 0;
            const score = upvotes - downvotes;

            const realCount = it.verifications?.filter((v) => v.is_real).length || 0;
            const accurateCount = it.verifications?.filter((v) => v.is_accurate).length || 0;
            const isAiGenerated = it.user_id === "ai-planner";

            return (
              <div key={it.id} className={`itinerary-card ${isAiGenerated ? "ai-card" : ""}`}>
                <div className="card-header">
                  <div className="card-badge-row">
                    <span className="badge badge-budget">{it.budget}</span>
                    {isAiGenerated ? (
                      <span className="badge badge-ai-planner">
                        <Sparkles size={10} /> AI Planner
                      </span>
                    ) : (
                      <>
                        {realCount > 0 && (
                          <span className="badge badge-real">
                            ✓ {realCount} Real
                          </span>
                        )}
                        {accurateCount > 0 && (
                          <span className="badge badge-accurate">
                            ★ {accurateCount} Accurate
                          </span>
                        )}
                      </>
                    )}
                  </div>
                  
                  <h3 className="card-title">
                    <Link href={`/itinerary/${it.id}`}>{it.title}</Link>
                  </h3>
                  
                  <div className="card-meta">
                    <span className="meta-item">
                      <MapPin size={14} /> {it.location}
                    </span>
                    <span className="meta-item">
                      <Calendar size={14} /> {it.duration_days} Days
                    </span>
                  </div>
                </div>

                <div className="card-body">
                  <p className="card-description">{it.description}</p>
                </div>

                <div className="card-footer">
                  <div className="author-info">
                    {isAiGenerated ? (
                      <div className="author-img-ai">
                        ✨
                      </div>
                    ) : it.author_image ? (
                      <img src={it.author_image} alt={it.author_name} className="author-img" />
                    ) : (
                      <div className="author-img-placeholder">
                        {it.author_name.charAt(0)}
                      </div>
                    )}
                    <span>By {it.author_name}</span>
                  </div>

                  <div className="card-metrics">
                    <span className="metric-item">
                      <ArrowUp size={16} /> {score}
                    </span>
                    <span className="metric-item">
                      <MessageSquare size={16} /> {it.comments?.length || 0}
                    </span>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
