import { getItineraries } from "../actions";
import Link from "next/link";
import { Search, MapPin, Calendar, ArrowUp, MessageSquare, Sparkles, Filter, RefreshCw } from "lucide-react";

export default async function ExplorePage({ searchParams }) {
  const resolvedSearchParams = await searchParams;
  const query = resolvedSearchParams?.q || "";
  const budget = resolvedSearchParams?.budget || "All";
  const duration = resolvedSearchParams?.duration || "All";
  const tab = resolvedSearchParams?.tab || "all";

  // Fetch filtered itineraries
  const itineraries = await getItineraries(query, { budget, duration, tab });

  // Helper to build URLs maintaining active filters
  const getFilterUrl = (key, value) => {
    const params = new URLSearchParams();
    if (query) params.set("q", query);
    if (budget !== "All") params.set("budget", budget);
    if (duration !== "All") params.set("duration", duration);
    if (tab !== "all") params.set("tab", tab);

    if (value === "All" || value === "all") {
      params.delete(key);
    } else {
      params.set(key, value);
    }

    const queryStr = params.toString();
    return `/explore${queryStr ? `?${queryStr}` : ""}`;
  };

  return (
    <div>
      {/* Header */}
      <div style={{ marginBottom: "2.5rem", textAlign: "center" }}>
        <h1 style={{ fontSize: "2rem", marginBottom: "0.5rem" }}>
          Explore Travel <span>Itineraries</span>
        </h1>
        <p style={{ color: "var(--text-muted)", fontSize: "0.95rem" }}>
          Find, verify, and copy plans shared by the community or generated by AI.
        </p>
      </div>

      {/* Search Input Container */}
      <form action="/explore" method="GET" className="search-container">
        {budget !== "All" && <input type="hidden" name="budget" value={budget} />}
        {duration !== "All" && <input type="hidden" name="duration" value={duration} />}
        {tab !== "all" && <input type="hidden" name="tab" value={tab} />}
        
        <Search className="search-icon" size={20} />
        <input
          type="text"
          name="q"
          defaultValue={query}
          placeholder="Search by destination (e.g. Delhi, Paris, Tokyo)..."
          className="search-input"
        />
      </form>

      {/* Tabs (All, Community, AI) */}
      <div style={{ display: "flex", gap: "0.5rem", borderBottom: "1px solid var(--surface-border)", marginBottom: "2rem", paddingBottom: "0.5rem", overflowX: "auto" }}>
        <Link 
          href={getFilterUrl("tab", "all")} 
          className={`btn ${tab === "all" ? "btn-primary" : "btn-secondary"}`}
          style={{ textTransform: "none", fontSize: "0.8rem", padding: "0.5rem 1rem", borderRadius: "20px" }}
        >
          All Guides
        </Link>
        <Link 
          href={getFilterUrl("tab", "community")} 
          className={`btn ${tab === "community" ? "btn-primary" : "btn-secondary"}`}
          style={{ textTransform: "none", fontSize: "0.8rem", padding: "0.5rem 1rem", borderRadius: "20px" }}
        >
          👤 Community Posted
        </Link>
        <Link 
          href={getFilterUrl("tab", "ai")} 
          className={`btn ${tab === "ai" ? "btn-primary" : "btn-secondary"}`}
          style={{ textTransform: "none", fontSize: "0.8rem", padding: "0.5rem 1rem", borderRadius: "20px" }}
        >
          ✨ Generated by AI
        </Link>
      </div>

      {/* Filter Widgets Panel */}
      <div style={{ background: "var(--surface)", border: "1px solid var(--surface-border)", borderRadius: "var(--radius-md)", padding: "1.25rem 1.5rem", marginBottom: "2rem" }}>
        <div style={{ display: "flex", flexWrap: "wrap", gap: "2rem", alignItems: "center", justifyContent: "space-between" }}>
          
          <div style={{ display: "flex", flexWrap: "wrap", gap: "1.5rem", alignItems: "center" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", color: "var(--text-muted)", fontSize: "0.85rem", fontWeight: "700" }}>
              <Filter size={14} /> FILTERS:
            </div>

            {/* Budget Filter */}
            <div style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
              <span style={{ fontSize: "0.8rem", color: "var(--text-muted)" }}>Budget:</span>
              <div style={{ display: "flex", gap: "0.25rem" }}>
                {["All", "Budget", "Mid-range", "Luxury"].map((b) => (
                  <Link
                    key={b}
                    href={getFilterUrl("budget", b)}
                    style={{
                      fontSize: "0.75rem",
                      padding: "0.35rem 0.65rem",
                      borderRadius: "4px",
                      background: budget === b ? "var(--primary)" : "rgba(255,255,255,0.03)",
                      color: budget === b ? "var(--text-inverse)" : "var(--text)",
                      textDecoration: "none",
                      fontWeight: "700",
                      border: "1px solid var(--surface-border)"
                    }}
                  >
                    {b}
                  </Link>
                ))}
              </div>
            </div>

            {/* Duration Filter */}
            <div style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
              <span style={{ fontSize: "0.8rem", color: "var(--text-muted)" }}>Duration:</span>
              <div style={{ display: "flex", gap: "0.25rem" }}>
                {[
                  { label: "All", value: "All" },
                  { label: "1-3 Days", value: "short" },
                  { label: "4-7 Days", value: "medium" },
                  { label: "8+ Days", value: "long" }
                ].map((d) => (
                  <Link
                    key={d.value}
                    href={getFilterUrl("duration", d.value)}
                    style={{
                      fontSize: "0.75rem",
                      padding: "0.35rem 0.65rem",
                      borderRadius: "4px",
                      background: duration === d.value ? "var(--primary)" : "rgba(255,255,255,0.03)",
                      color: duration === d.value ? "var(--text-inverse)" : "var(--text)",
                      textDecoration: "none",
                      fontWeight: "700",
                      border: "1px solid var(--surface-border)"
                    }}
                  >
                    {d.label}
                  </Link>
                ))}
              </div>
            </div>
          </div>

          {/* Reset Filters Option */}
          {(query || budget !== "All" || duration !== "All" || tab !== "all") && (
            <Link 
              href="/explore"
              className="btn btn-secondary"
              style={{ padding: "0.4rem 0.8rem", fontSize: "0.75rem" }}
            >
              <RefreshCw size={12} /> Clear Filters
            </Link>
          )}
        </div>
      </div>

      {/* Results Header */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "1.5rem" }}>
        <h2 style={{ fontSize: "1.1rem", fontWeight: "700" }}>
          {query ? `Search Results for "${query}"` : `${tab === "ai" ? "AI Generated" : tab === "community" ? "Community" : "Trending"} Guides`}
        </h2>
        <span style={{ color: "var(--text-muted)", fontSize: "0.85rem" }}>
          Showing {itineraries.length} guides
        </span>
      </div>

      {/* Itineraries Grid */}
      {itineraries.length === 0 ? (
        <div style={{ textAlign: "center", padding: "4rem 2rem", background: "var(--surface)", borderRadius: "var(--radius-md)", border: "1px solid var(--surface-border)" }}>
          <MapPin size={48} style={{ color: "var(--text-muted)", marginBottom: "1rem" }} />
          <h3>No itineraries found</h3>
          <p style={{ color: "var(--text-muted)", marginTop: "0.5rem" }}>
            Adjust your search query or remove active filters to browse more itineraries.
          </p>
        </div>
      ) : (
        <div className="itinerary-grid">
          {itineraries.map((it) => {
            const upvotes = it.votes?.filter((v) => v.vote_type === "upvote").length || 0;
            const downvotes = it.votes?.filter((v) => v.vote_type === "downvote").length || 0;
            const score = upvotes - downvotes;

            const realCount = it.verifications?.filter((v) => v.is_real).length || 0;
            const accurateCount = it.verifications?.filter((v) => v.is_accurate).length || 0;
            const isAiGenerated = it.user_id === "ai-planner";

            return (
              <div key={it.id} className="itinerary-card" style={isAiGenerated ? { border: "1px solid rgba(218, 248, 113, 0.25)" } : {}}>
                <div className="card-header">
                  <div className="card-badge-row">
                    <span className="badge badge-budget">{it.budget}</span>
                    {isAiGenerated ? (
                      <span className="badge" style={{ background: "rgba(218, 248, 113, 0.15)", color: "var(--primary)", border: "1px solid rgba(218, 248, 113, 0.3)", display: "inline-flex", alignItems: "center", gap: "0.25rem" }}>
                        <Sparkles size={10} /> AI Planner
                      </span>
                    ) : (
                      <>
                        {realCount > 0 && (
                          <span className="badge badge-real">
                            ✓ {realCount} Real
                          </span>
                        )}
                        {accurateCount > 0 && (
                          <span className="badge badge-accurate">
                            ★ {accurateCount} Accurate
                          </span>
                        )}
                      </>
                    )}
                  </div>
                  
                  <h3 className="card-title">
                    <Link href={`/itinerary/${it.id}`}>{it.title}</Link>
                  </h3>
                  
                  <div className="card-meta">
                    <span style={{ display: "flex", alignItems: "center", gap: "0.25rem" }}>
                      <MapPin size={14} /> {it.location}
                    </span>
                    <span style={{ display: "flex", alignItems: "center", gap: "0.25rem" }}>
                      <Calendar size={14} /> {it.duration_days} Days
                    </span>
                  </div>
                </div>

                <div className="card-body">
                  <p className="card-description">{it.description}</p>
                </div>

                <div className="card-footer">
                  <div className="author-info">
                    {isAiGenerated ? (
                      <div className="author-img" style={{ background: "var(--primary)", display: "flex", alignItems: "center", justifyContent: "center", color: "var(--text-inverse)", fontWeight: "bold" }}>
                        ✨
                      </div>
                    ) : it.author_image ? (
                      <img src={it.author_image} alt={it.author_name} className="author-img" />
                    ) : (
                      <div className="author-img" style={{ background: "rgba(255,255,255,0.1)", display: "flex", alignItems: "center", justifyContent: "center", color: "white", fontWeight: "bold", fontSize: "0.7rem" }}>
                        {it.author_name.charAt(0)}
                      </div>
                    )}
                    <span>By {it.author_name}</span>
                  </div>

                  <div style={{ display: "flex", gap: "1rem", color: "var(--text-muted)", fontSize: "0.85rem", alignItems: "center" }}>
                    <span style={{ display: "flex", alignItems: "center", gap: "0.25rem" }}>
                      <ArrowUp size={16} /> {score}
                    </span>
                    <span style={{ display: "flex", alignItems: "center", gap: "0.25rem" }}>
                      <MessageSquare size={16} /> {it.comments?.length || 0}
                    </span>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
